# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'DistDownloadExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DistDownloadExample
  pod 'ASIHTTPRequest', '~> 1.8.2'

  target 'DistDownloadExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DistDownloadExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
